### ISSUE TITLE
The integration guide for TagoIO brings up a "Device EUI" parameter that is non-existent on V3

### ISSUE THREAD

**Issue by HouzuoGuo** [TheThingsIndustries/lorawan-stack-docs#291]
#### Summary
The integration guide for TagoIO brings up a "Device EUI" parameter that is non-existent on V3.

#### What is already there? What do you see now?
On this page: https://www.thethingsindustries.com/docs/integrations/cloud-integrations/tagoio/

A paragraph says: "Give a name to your device by filling the Device name field, enter the Device EUI and click the Create my device button to finish."

#### What is missing? What do you want to see?
Unlike the old V2 TTN console, the V3 console "The Things Stack" no longer displays devices' EUI.

#### How do you propose to document this?
A couple of ways:

- Ideally, the V3 console should be improved in this regard, match the capabilities offered by the V2 console previously and bring back the device's EUI display.
- If the V2 console calculates device EUI according to a formula derived from other parameters visible to the console user, then please state the formula so that a user can perform the calculation manually.

#### Can you do this yourself and submit a Pull Request?
Not quite

**Comment by nejraselimovic** [comment]
If you have a device at your site, you should already know the DevEUI. Quoting the [glossary]: 

> A 64 bit extended unique identifier for your device. This is programmed by the manufacturer and should not be changed. It should be provided to you by the manufacturer, or printed on the device.

In case it's not printed on the box or the device itself, there should be a tutorial specific for your device on how to find out the DevEUI (for example, for Arduino based devices it is possible by connecting it to your PC and printing the board info through Arduino IDE).

For the record, V2 Console was not "displaying" the DevEUI but you had two available options - to enter it by yourself or to autogenerate one. Autogenerating the DevEUI is not going to be implemented in V3, because this value shouldn't be changed at all (it was an experimental option in V2). If you enter the DevEUI by yourself as you should, then you will see the DevEUI displayed in your device's settings.
