### ISSUE TITLE
Document DNS service discovery

### ISSUE THREAD

**Issue by adriansmares** [TheThingsIndustries/lorawan-stack-docs#811]
#### Summary

The DNS service discovery (used by clustering) that is part of the Enterprise distribution is not documented.

#### Why do we need this ?

Customers that would like to scale out from single instance Enterprise distributions currently do not have a clear documentation on how to use DNS service discovery in order to connect components. 

#### What is already there? What do you see now?

DNS service discovery, used for peer communication, but not documented.

#### What is missing? What do you want to see?

Documentation on how it works, and how it can be used in order to connect service instances.

#### How do you propose to document this?

Document the cluster peer discovery mode `dns`, then mention the structure of the `A`/`SRV` records.

#### Can you do this yourself and submit a Pull Request?

Can review.

**Comment by htdvisser** [comment]
I don't think we should do this. We want our customers to use the supported deployment models, where clustering is tested by us, and where we know how to debug any issues. If we document the internals of clustering, customers _will_ use it incorrectly and come to us for more support, which is exactly what we don't want.

I'm fine with documenting the details for internal use, but I think the implementation is already quite clear, especially since @adriansmares's changes in https://github.com/TheThingsIndustries/lorawan-stack/pull/3081.
