### ISSUE TITLE
Unexplained "stringToString" format in CLI reference

### ISSUE THREAD

**Issue by EveUbees** [TheThingsIndustries/lorawan-stack-docs#974]
I cannot find what does "stringToString" mean in CLI documentation.

I want to use "ttn-lw-cli gateways set --attribute" command line, but it does not explain how to format the key:value entry.
The command line helpfully gives the answer:
"invalid argument "toto:titi" for "--attributes" flag: map flag values must be formatted as key=value"

But the documentation does not:
https://www.thethingsindustries.com/docs/ttn-lw-cli/ttn-lw-cli_gateways_set/
"ttn-lw-cli gateways set
Set properties of a gateway
ttn-lw-cli gateways set [gateway-id] [flags]

Options
[...]
      --antenna.gain float32                                                 
      --antenna.index int                                                    index of the antenna to update or remove
      --antenna.location.accuracy int32    
[...]
      --attributes stringToString"

**Comment by nejraselimovic** [comment]
Hmm, I'm not sure about this. This documentation is auto-generated I think. @johanstokking can you help?

**Comment by johanstokking** [comment]
Indeed, this is going to be very tricky. This piece of the codebase is the oldest we have so that doesn't help either. I'm gonna close this now, as indeed the error message is self explaining. If users find that really problematic, let's revisit. In that case, please reopen the issue and we'll gather some upvotes to address this.

**Comment by EveUbees** [comment]
OK, got it!
Thank you for your time!
Eve
